name: semver-bump

on: [push]

env:
  DEPLOY_KEY: ${{ secrets.SSH_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: semver
      run: |
        git describe --tags

    # - name: deploy
    #   run: |
    #     docker run --rm qwertmax/ssh bash -c '${{ secrets.CMD}}'
      env:
        CI: true

        # ver=$(git describe --tags)
        # new_ver=$(docker run --rm alpine/semver semver -c -i patch $ver)
        # echo $ver
        # echo $new_ver
        # git tag v$new_ver
        # git push --tags
