name: semver-bump

on: [push]

env:
  DEPLOY_KEY: ${{ secrets.SSH_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: semver
      run: |
        version=$(cat VERSION)
        echo "version: $version"
        docker run --rm alpine/semver semver -c -i patch $version > VERSION
        git config --global user.email "qwertmax@gmail.com"
        git config --global user.name "Maxim Tishchento"
        git add -A
        git commit -m "version $version"
        git tag -a "$version" -m "version $version"
        git push
        git push --tags

    # - name: deploy
    #   run: |
    #     docker run --rm qwertmax/ssh bash -c '${{ secrets.CMD}}'
      env:
        CI: true