name: semver-bump

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # - name: npm install, build, and test
    #   run: |
    #     docker run --rm alpine/semver semver -c -i minor 1.0.2
    #     echo ${{ secrets.SSH_KEY }} > dev-ecs.pem
    #     ssh -i "dev-ecs.pem" ec2-user@ec2-18-224-16-242.us-east-2.compute.amazonaws.com ./deploy.sh

    - name: npm install, build, and test
      run: |
        ls -la
        whereis ssh
      env:
        CI: true
