name: semver-bump

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DEPLOY_KEY: ${{ secrets.SSH_KEY }}
  USERNAME: qwertmax
  IMAGE: test-semver

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: create VERSION
      run: |
        echo 1.0.0 > VERSION

    - name: Upload VERSION
      uses: actions/upload-artifact@v1
      with:
        name: version
        path: VERSION

    - name: print VERSION
      run: |
        ls -la
        ls -la version



    # - name: semver
    #   run: |
    #     version=$(cat VERSION)
    #     echo "version: $version"
    #     docker run --rm alpine/semver semver -c -i patch $version > VERSION
    #     git config --global user.email "qwertmax@gmail.com"
    #     git config --global user.name "Maxim Tishchento"
    #     git checkout -b build
    #     git merge master
    #     git add -A
    #     git commit -m "version $version"
    #     git tag -a "$version" -m "version $version"
    #     git push --set-upstream origin build
    #     git push --tags

    # - name: login
    #   run: |
    #     version=$(cat VERSION)
    #     echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

    # - name: build
    #   run: |
    #     version=$(cat VERSION)
    #     docker build -t $USERNAME/$IMAGE . 
    #     docker tag $USERNAME/$IMAGE:latest $USERNAME/$IMAGE:$version

    # - name: deploy
    #   run: |
    #     version=$(cat VERSION)
    #     docker push $USERNAME/$IMAGE:latest
    #     docker push $USERNAME/$IMAGE:$version

    # - name: deploy
    #   run: |
    #     docker run --rm qwertmax/ssh bash -c '${{ secrets.CMD}}'
      env:
        CI: true