name: semver-bump

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DEPLOY_KEY: ${{ secrets.SSH_KEY }}
  USERNAME: qwertmax
  IMAGE: test-semver

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: semver
      run: |
        git fetch --all --tags
        version=$(git describe --tags --abbrev=0)
        echo "version: $version"
        version=$(docker run --rm alpine/semver semver -c -i patch $version)
        git config --global user.email "qwertmax@gmail.com"
        git config --global user.name "Maxim Tishchento"
        git tag -a "$version" -m "version $version"
        git push --tags


    - name: login
      run: |
        version=$(cat VERSION)
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

    - name: build
      run: |
        version=$(cat VERSION)
        docker build -t $USERNAME/$IMAGE . 
        docker tag $USERNAME/$IMAGE:latest $USERNAME/$IMAGE:$version

    - name: deploy
      run: |
        version=$(cat VERSION)
        docker push $USERNAME/$IMAGE:latest
        docker push $USERNAME/$IMAGE:$version

    # - name: deploy
    #   run: |
    #     docker run --rm qwertmax/ssh bash -c '${{ secrets.CMD}}'
      env:
        CI: true