name: semver-bump

on: [push]

env:
  DEPLOY_KEY: ${{ secrets.SSH_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: semver
      run: |
        ver=$(git describe --abbrev=0 --tags)
        new_ver=$(docker run --rm alpine/semver semver -c -i patch $ver)
        git tag $new_ver
        git push --tags

    # - name: deploy
    #   run: |
    #     docker run --rm qwertmax/ssh bash -c '${{ secrets.CMD}}'
      env:
        CI: true
