name: semver-bump

on: [push]

env:
  DEPLOY_KEY: ${{ secrets.SSH_KEY }}
  VERSION: ${{ secrets.VERSION }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: semver
      run: |
        


    # - name: deploy
    #   run: |
    #     docker run --rm qwertmax/ssh bash -c '${{ secrets.CMD}}'
      env:
        CI: true
